# Generated by Django 2.0.7 on 2018-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='isDelete',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='tAge',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='tName',
            field=models.CharField(default='linhongcun', max_length=20),
        ),
    ]
