# Generated by Django 2.0.7 on 2018-07-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180703_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentInfo',
            new_name='student_info',
        ),
    ]
