# Generated by Django 2.0.7 on 2018-07-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180703_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='tAge',
            new_name='t_age',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='tImage',
            new_name='t_image',
        ),
        migrations.RenameField(
            model_name='student_info',
            old_name='tName',
            new_name='t_name',
        ),
    ]
